block: bfq: Fix derp after commit 237f27c
../block/bfq-iosched.c: In function ‘bfq_merge’:
../block/bfq-iosched.c:1649:14: error: implicit declaration of function ‘elv_rq_merge_ok’; did you mean ‘blk_rq_merge_ok’? [-Werror=implicit-function-declaration]
  if (__rq && elv_rq_merge_ok(__rq, bio)) {
              ^~~~~~~~~~~~~~~
              blk_rq_merge_ok
../block/bfq-iosched.c: At top level:
../block/bfq-iosched.c:5271:4: error: ‘struct elevator_ops’ has no member named ‘elevator_allow_merge_fn’; did you mean ‘elevator_allow_rq_merge_fn’?
   .elevator_allow_merge_fn = bfq_allow_merge,
    ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>