sched: Fix build
../kernel/sched/core.c:1295:2: error: implicit declaration of function 'SCHED_WARN_ON' [-Werror,-Wimplicit-function-declaration]
        SCHED_WARN_ON(!bucket->tasks);
        ^

The macro SCHED_WARN_ON was added in v4.9+.
When CONFIG_SCHED_DEBUG is not defined, SCHED_WARN_ON will do nothing.
We ignore it for now.

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>