drivers/md: dm-req-crypt: Remove SECTOR_SIZE macro definition
After merge v4.4.259 definition of SECTOR_SIZE has been moved to
"include/linux/blkdev.h", but in "drivers/md/dm-req-crypt.c"
definition of SECTOR_SIZE has not been removed and this raises
following warning message:

./drivers/md/dm-req-crypt.c:48: warning: "SECTOR_SIZE" redefined
   48 | #define SECTOR_SIZE 512
      |
In file included from ../drivers/md/dm-req-crypt.c:18:
../include/linux/blkdev.h:851: note: this is the location of the previous definition
  851 | #define SECTOR_SIZE (1 << SECTOR_SHIFT)
      |

So remove redefinition of SECTOR_SIZE in "drivers/md/dm-req-crypt.c"
so as not to raise any more warning messages.

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>