input/touchscreen: nvt_touch_d2s: Remove redefinition some functions
* This is a fix of commit ae90c3baf2aa098ef0cb3b067d9be1734346cc63.

./drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:314:12: error: redefinition of 'nvt_gesture_read'
  314 | static int nvt_gesture_read(struct seq_file *file, void *v)
      |            ^~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:275:12: note: previous definition of 'nvt_gesture_read' was here
  275 | static int nvt_gesture_read(struct seq_file *file, void *v)
      |            ^~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:319:13: error: redefinition of 'nvt_gesture_open'
  319 |  static int nvt_gesture_open(struct inode *inode, struct file *file)
      |             ^~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:281:12: note: previous definition of 'nvt_gesture_open' was here
  281 | static int nvt_gesture_open(struct inode *inode, struct file *file)
      |            ^~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:323:17: error: redefinition of 'nvt_gesture_write'
  323 |  static ssize_t nvt_gesture_write(struct file *file, const char __user *buf,
      |                 ^~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:286:16: note: previous definition of 'nvt_gesture_write' was here
  286 | static ssize_t nvt_gesture_write(struct file *file, const char __user *buf,
      |                ^~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:331:38: error: redefinition of 'nvt_gesture_fops'
  331 |  static const struct file_operations nvt_gesture_fops = {
      |                                      ^~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nvt_touch_d2s/nt36xxx.c:295:37: note: previous definition of 'nvt_gesture_fops' was here
  295 | static const struct file_operations nvt_gesture_fops = {
      |                                     ^~~~~~~~~~~~~~~~

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>